Debugging wilee test execution

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -49,10 +49,12 @@ steps:
     chmod +x wilee
     ls -l wilee
     APP=http://localhost:8080 TESTCASES=test/api/*.wilee.json ./wilee
-    TESTRESULTS=$(cat test/api/*.result.json)
-    echo $TESTRESULTS
-    echo $TESTRESULTS | jq '.test_info.id, .pass_fail, .pass_fail_reason'
     kill $APP_PID
+    TESTRESULTS=$(cat test/api/*.result.json)
+    echo $TESTRESULTS | jq '.'
+    echo $TESTRESULTS | jq '.test_info.id, .pass_fail, .pass_fail_reason'
+    FAILED_TESTS=$(echo $TESTRESULTS | jq '.pass_fail' | grep fail | wc -l)
+    if [ $FAILED_TESTS -gt 0 ]; then echo $FAILED_TESTS "API tests failed" && exit 1; fi
   displayName: 'Run wilee API tests'
 
 - script: |
