Debugging Artillery reporting

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -153,13 +153,13 @@ steps:
     # Run the artillery load test
     artillery run -o TEST-artillery.json test/performance/performance.yml
 
+    # If test fails, exit 1 to fail this step in the pipeline
+    if [ $? -ne 0 ]; then kill $APP_PID && exit 1; fi
+
     # Generate the Artillery test report
     artillery report TEST-artillery.json
 
     ls -l
-
-    # If test fails, exit 1 to fail this step in the pipeline
-    if [ $? -ne 0 ]; then kill $APP_PID && exit 1; fi
 
     # Display Artillery test results in log
     cat TEST-artillery.json
